### ISSUE TITLE
backend.iobio.io is currently hard coded for geneinfo requests

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#100]

**Comment by YangQi007** [comment]
@anderspitman I remember you said before that we better build a small gene database instead of querying the gene from the endpoint. 

Is that what you mean for this issue?

**Comment by anderspitman** [comment]
No this is a different one. What I mean is that the requests are hard coded to use backend.iobio.io. See here:

https://github.com/iobio/iobio-charts/blob/d6672a72a7aac960ba8060179274b40c9b5a591e/coverage/src/BamView-WebComponent.js#L238

We want to be able to override what server is used, for people who want to run their own iobio backend (like OICR may want to). For example, you can see how Mosaic overrides the backend starting here: https://github.com/iobio/bam.iobio/blob/58bae164d91b44e673fa0ee83ccb37334c8c179b/index.html#L295

**Comment by anderspitman** [comment]
@YangQi007 this one is done right?

**Comment by YangQi007** [comment]
> @YangQi007 this one is done right?

Yes
