### ISSUE TITLE
Read depth chart color looks too light, probably due to gaps

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#23]

**Comment by anderspitman** [comment]
I don't think this one is fixed yet. The bars still look lighter than the other charts, which are set to the same color. We don't need to fix this right now but I would like to eventually see if there's a solution. I suspect we need bigger bins, which would also improve rendering performance.

**Comment by YangQi007** [comment]
I only fixed the gaps. I'll look into the color later.
