### ISSUE TITLE
Read depth chart doesn't limit the number of chromosomes shown

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#37]
This can happen if there are a lot of "decoy references"

**Comment by anderspitman** [comment]
@YangQi007 this one is ready for you. Basically we only want to show chromosomes that have lots of data to the user. I added the `getValidRefs` function that you can use to get a list of which ones to show. You can see an example of how I use it here:

https://github.com/iobio/iobio-charts/blob/5dc1aec1b450a976a2b0447599353d8b5f7ae691/data_broker.js#L139

Let me know if you have any questions

**Comment by anderspitman** [comment]
You can launch iobio for this sample to see one with thousands of refs: https://mosaic-staging.chpc.utah.edu/#/projects/476/samples/19863/overview

**Comment by YangQi007** [comment]
@anderspitman Thanks for this helper function. It's easy to get a valid header and read depth data.
