### ISSUE TITLE
Investigate the white gaps in charts

### ISSUE THREAD

**Issue by YangQi007** [iobio/iobio-charts#51]
There are white gaps between bars in the chrome browser but not in the Firefox.

**Comment by anderspitman** [comment]
This was caused by not setting `shape-rendering: crispEdges;` in CSS. You can see where bam1 does it here: https://github.com/iobio/bam.iobio.io/blob/bfd3b485d5b08ae3011c016a2790329622bb8de0/client/app/components/viz/StackedHistogram.vue#L14

Fixed now

**Comment by anderspitman** [comment]
@YangQi007 you might be interested in the knowing the solution

**Comment by anderspitman** [comment]
Fixed in https://github.com/iobio/iobio-charts/commit/7a34d45704320e2e5841319348b28e03ad494591
