### ISSUE TITLE
Make wrapper component for switch between 2 sub-components

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#66]
This is what production bam does for the histograms

**Comment by YangQi007** [comment]
Will we keep the same switch button to control the histogram charts? In our bam2, the histogram's title is created in the customized component. And user can change it according to their preferences.

**Comment by anderspitman** [comment]
I think we want a more generic switcher that can hold any 2 components, even if they are completely different types. Maybe using web component slots?

**Comment by anderspitman** [comment]
```html
<iobio-tabs
  label-1="Fragment Length"
  label-2="Read Length"
>
  <iobio-histogram
    broker-key="frag_hist"
    ignore-outliers>
  </iobio-histogram>
  <iobio-histogram
    broker-key="length_hist"
    ignore-outliers>
  </iobio-histogram>
</iobio-tabs>
```

**Comment by YangQi007** [comment]
I tried the structure you suggested (please see the screenshot below). I didn't find a way to put the switch button inside the chart component similar to what bam1 did. 
<img width="745" alt="Screenshot 2024-07-29 at 12 32 45 PM" src="https://github.com/user-attachments/assets/c509e9d5-3e66-4454-b2c1-9397d646635a">

**Comment by anderspitman** [comment]
This looks pretty close overall. We should be able to get closer by adding a border to the wrapper and making the histogram border optional.

**Comment by YangQi007** [comment]
> This looks pretty close overall. We might be able to get closer by adding a border to the wrapper and making the histogram border optional.

Are you saying that we can add a "ignore-border" option similar to what you did for "ignore-outlier"
