### ISSUE TITLE
Use the same color of blue for data, and let it be overridden with a CSS variable

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#7]

**Comment by anderspitman** [comment]
@YangQi007 this took a while to figure out. You can see how I'm doing it here: https://github.com/iobio/iobio-charts/blob/367e64bcfb6dc2de33a024a706a09c37fbae4991/common.js#L4-L8

That let's you use `--data-color` internally, but override it with `--iobio-data-color` from outside the web component.

Let me know if you have any questions.

**Comment by YangQi007** [comment]
Where is the "--iobio-data-color" set up? Do you mean that the default color is #2d8fc1 and users can set up whatever they want for this variable?

**Comment by anderspitman** [comment]
Yes. They don't have to provide a value for `--iobio-data-color` if they're happy with the default

**Comment by anderspitman** [comment]
Fixed in #19
