### ISSUE TITLE
Emit region change events from the read depth chart

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#8]
Need to dispatch a [custom event](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events#adding_custom_data_%E2%80%93_customevent), probably with `bubbles` and `composed` set to true. See here: https://javascript.info/shadow-dom-events#custom-events

**Comment by anderspitman** [comment]
We probably need to emit 2 different events: region changes and chromosome selection. For now we're only going to resample for chromosome selection. It would be nice to dynamically resample whenever the user brushes but I think that might require backend changes.

**Comment by YangQi007** [comment]
I see. I'll make 1 emit event for chromosome selection first and leave the event of region changes later.
